WebAssignmentMVC-Louis/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAssignmentMVC.Models.Person;
using WebAssignmentMVC.Models.Person.Services;
using WebAssignmentMVC.Models.Person.ViewModels;

namespace WebAssignmentMVC.Controllers
{
    public class LanguageController : Controller
    {
        private readonly ILanguageService _languageService;
        private readonly IPeopleService _PeopleService;

        public LanguageController(ILanguageService languageService, IPeopleService peopleService)
        {
            _languageService = languageService;
            _PeopleService = peopleService;
        }
        // GET: LanguageController
        public ActionResult Index()
        {
            return View(_languageService.GetAll());
        }

        // GET: LanguageController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LanguageController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LanguageController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateLanguageViewModel createLanguage)
        {
            if (ModelState.IsValid)
            {
                Language language = _languageService.Create(createLanguage);
                if (language != null)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("System", "Fail to create language!!!");
            }
            return View(createLanguage);
        }

        // GET: LanguageController/Edit/5
        public ActionResult Edit(int id)
        {
            Language lang = _languageService.FindById(id);

            if (lang == null)
            {
                return RedirectToAction(nameof(Index));
            }

            CreateLanguageViewModel editLanguage = new CreateLanguageViewModel()
            {
                LangName = lang.LangName
            };

            ViewBag.id = id;

            return View(editLanguage);
        }

        // POST: LanguageController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CreateLanguageViewModel language)
        {
            if (ModelState.IsValid)
            {
                if (_languageService.Edit(id, language) != null)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("System", "Fail to edit Language!!!");
            }
            ViewBag.id = id;
            return View(language);
        }


        // GET: LanguageController/Delete/5
        public ActionResult Delete(int id)
        {
            Language lang = _languageService.FindById(id);

            if (lang != null)
            {
                if (_languageService.Remove(id))
                    return RedirectToAction(nameof(Index));
                else
                {
                    ModelState.AddModelError("System", "Fail to delete Language!!!");
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: LanguageController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
                if (_languageService.Remove(id))
                    return RedirectToAction(nameof(Index));
                else
                {
                    ModelState.AddModelError("System", "Fail to delete language!!!");
                }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult AddPerson(int id)
        {
            List<PersonLanguage> lang = _PeopleService.GetLanguage(id);
            List<Person> allPerson = _PeopleService.All();
            if (lang == null)
            {
                return RedirectToAction(nameof(Index));
            }
            PersonLanguage showLang = new PersonLanguage();
            if (showLang != null)
            {
            showLang.LanguageId = id;
            ViewBag.LangName = _languageService.GetLanguageName(id);
            ViewBag.Id = id;
            }
            ViewBag.Persons = allPerson;

            return View();  
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPerson(PersonLanguage langPerson, int id)
        {
            var fromPerson = HttpContext.Request.Form["PersonId"];
            langPerson.LanguageId = id;
            langPerson.Person = _PeopleService.FindById(id);
            langPerson.Language = _languageService.FindById(id);
            List<Person> maxPerson = _PeopleService.All();
            List<Language> maxLang = _languageService.GetAll();
            List<Person> toAddPer = new List<Person>();
            int count = 0;
            foreach (Person person in maxPerson)
            {
                if (count <= fromPerson.Count - 1)
                {
                    toAddPer.Add(new Person { Id = int.Parse(fromPerson[count]) });
                    count++;
                }
            }
            if (ModelState.IsValid)
            {
                if (langPerson != null)
                {
                    _languageService.AddLang(langPerson, toAddPer);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();
        }
        public IActionResult GetLanguages()
        {
            return Json(_languageService.GetAll());
        }
    }
}

WebAssignmentMVC-Louis/Views/Language/AddPerson.cshtml
@model WebAssignmentMVC.Models.Person.PersonLanguage
<h2>Add Person to Language</h2>
<hr />

<div class="col-md-4">
    <form method="post">
        <input type="hidden" asp-for="LanguageId" name="LanguageId"/>
        <div class="form-group">
            <label>Language</label>
            <div class="font-weight-bold">
                <h2>
                    @ViewBag.LangName
                </h2>
            </div>

        </div>
        <div class="form-group">
            <label asp-for="PersonId">Person List</label>
            @Html.DropDownList("PersonId", new SelectList(ViewBag.Persons, "Id", "FirstName", "LastName"), 
           new { @class = "multi-select", multiple = "multiple", style = "width: 100px;" })

        </div>
        <div class="form-group">
            <button onclick="@Url.Action("AddPerson", "Language")" type="submit">Add</button>
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Back to Language List</a>
</div>

WebAssignmentMVC-Louis/Views/Language/Create.cshtml
@model WebAssignmentMVC.Models.Person.ViewModels.CreateLanguageViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Language</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LangName" class="control-label"></label>
                <input asp-for="LangName" class="form-control" />
                <span asp-validation-for="LangName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebAssignmentMVC-Louis/Views/Language/Edit.cshtml
@model WebAssignmentMVC.Models.Person.ViewModels.CreateLanguageViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Language</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LangName" class="control-label"></label>
                <input asp-for="LangName" class="form-control" />
                <span asp-validation-for="LangName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAssignmentMVC-Louis/Views/Language/Index.cshtml
@model List<Language>
@{
    ViewData["Title"] = "Index Language";
}


<h1>Language List</h1>
<a asp-action="Create" class="btn-secondary mt-4 mb-4">Add new Language</a>
<table class="contact">
    <tr>
        <th>ID</th>
        <th>Language</th>
        <th>Actions</th>
    </tr>
    <tbody>
        @foreach (Language language in Model)
        {
            <tr>
                <td>@language.Id</td>
                <td>@language.LangName.</td>
                <td>
                    <a asp-controller="Language" asp-action="AddPerson" asp-route-id="@language.Id" class="mr-4 text-info">Add Person</a>
                    <a asp-action="Edit" asp-controller="Language" asp-route-id="@language.Id" class="mr-4 text-warning">Edit</a>
                    <a asp-action="Delete" asp-controller="Language" asp-route-id="@language.Id" class="mr-4 text-danger">Delete</a>

                </td>
            </tr>
        }
    </tbody>
</table>
@if (ViewBag.msg != null)
{
    <h3>@ViewBag.msg</h3>
}