WebAssignmentMVC-Louis/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAssignmentMVC.Models.Person;
using WebAssignmentMVC.Models.Person.Data;
using WebAssignmentMVC.Models.Person.Services;
using WebAssignmentMVC.Models.Person.ViewModels;

namespace WebAssignmentMVC.Controllers
{
    public class CitiesController : Controller
    {
        private readonly ICityService _cityService;
        private readonly ICountryService _countryService;

        public CitiesController(ICityService cityService, ICountryService countryService)
        {
            _cityService = cityService;
            _countryService = countryService;
        }

        // GET: Cities
        public ActionResult Index()
        {
            return View(_cityService.GetAll());
        }

        // GET: Cities/Details/5
        public IActionResult Details(int id)
        {
            string cityName = _cityService.FindById(id);
            return Json(cityName);
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
           CreateCityViewModel model = new CreateCityViewModel();
            model.CountryList = _countryService.GetAll();
            return View(model);
        }

        // POST: Cities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCityViewModel createCity)
        {
            if (ModelState.IsValid)
            {
               City cityView = _cityService.Create(createCity);
                if (cityView != null)
                {
                  return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("System", "Fail to Create City!!!");
            }
            createCity.CountryList = _countryService.GetAll();
            return View(createCity);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int id)
        {
            string city = _cityService.FindById(id);

            if (city == null)
            {
                return RedirectToAction(nameof(Index));
            }

            CreateCityViewModel editCity = new CreateCityViewModel()
            {
                CName = city
            };
            editCity.CountryList = _countryService.GetAll();

            ViewBag.id = id;

            return View(editCity);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, City city)
        {
            if (ModelState.IsValid)
            {
                if (_cityService.Edit(city) == true)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("System", "Fail to edit City!!!");
            }
            ViewBag.id = id;
            return View(city);
        }

        // GET: Cities/Delete/5
        public IActionResult Delete(int id)
        {

            if (_cityService.FindById(id) != null)
            {
                City city = _cityService.GetCity(id);
                if (_cityService.Remove(city))
                    return RedirectToAction(nameof(Index));
                else
                {
                    ModelState.AddModelError("System", "Fail to create country!!!");
                }
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult GetCities()
        {
            return Json(_cityService.GetAll());
        }

    }
}

WebAssignmentMVC-Louis/Controllers/CountryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAssignmentMVC.Models.Person;
using WebAssignmentMVC.Models.Person.Services;
using WebAssignmentMVC.Models.Person.ViewModels;

namespace WebAssignmentMVC.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICountryService _countryService;

        public CountryController(ICountryService countryService)
        {
            _countryService = countryService;
        }
        // GET: CountryController
        public ActionResult Index()
        {        
            return View(_countryService.GetAll());
        }

        // GET: CountryController/Details/5
        public ActionResult Details(int id)
        {
            // More coding..pending
            return View();
        }

        // GET: CountryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CountryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCountryViewModel createCountry)
        {
            if (ModelState.IsValid)
            {
                Country country = _countryService.Create(createCountry); 
                if (country != null)
                   return RedirectToAction(nameof(Index));
                ModelState.AddModelError("System", "Fail to create country!!!");
            }
                return View(createCountry);
        }

        // GET: CountryController/Edit/5
        public ActionResult Edit(int id)
        {
            Country country = _countryService.FindById(id);

            if (country == null)
            {
                return RedirectToAction(nameof(Index));
            }

            CreateCountryViewModel editCountry = new CreateCountryViewModel()
            {
                CountryName = country.Cname
            };


            ViewBag.id = id;

            return View(editCountry);
        }

        // POST: CountryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, CreateCountryViewModel country)
        {
            if (ModelState.IsValid)
            {
                if (_countryService.Edit(id, country) != null)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("System", "Fail to edit Country!!!");
            }
            ViewBag.id = id;
            return View(country);
        }

        // GET: CountryController/Delete/5
            public ActionResult Delete(int id)
        {
            Country country = _countryService.FindById(id);

            if (country != null)
            {
                if (_countryService.Remove(id))
                return RedirectToAction(nameof(Index));
                else
                {
                    ModelState.AddModelError("System", "Fail to delete country!!!");
                }
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult GetCountries()
        {
            return Json(_countryService.GetAll());
        }
    }
}

WebAssignmentMVC-Louis/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAssignmentMVC.Models.Person;
using WebAssignmentMVC.Models.Person.Repo;
using WebAssignmentMVC.Models.Person.Services;
using WebAssignmentMVC.Models.Person.ViewModels;

namespace WebAssignmentMVC.Controllers
{
    public class PersonController : Controller
    {
        private readonly ICityService _cityService;
        private readonly ICountryService _countryService;
        private readonly IPeopleService _peopleService;
        private readonly IPeopleRepo _memoryPeople;
        private readonly ILanguageRepo _languageService;

        public PersonController(ILanguageRepo languageRepo, IPeopleService peopleService, ICountryService countryService, IPeopleRepo memoryPeople, ICityService cityService)
        {
//            _memoryPeople = new IMemoryPeopleRepo();
            _peopleService = peopleService;
            _countryService = countryService;
            _memoryPeople = memoryPeople;
            _cityService = cityService;
            _languageService = languageRepo;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            List<Person> listPerson = _peopleService.All();
            string[] forLang= new string[listPerson.Count];
            List<PersonLanguage> chkLang = new List<PersonLanguage>();
            for(int i=1; i<listPerson.Count-1; i++)
            {
                
                listPerson[i].Country = _countryService.FindById(listPerson[i].CountryId);
                listPerson[i].Country.Cities = _cityService.GetAll();

                chkLang = _peopleService.GetLanguage(listPerson[i].Id);
                for (int j=0; j<chkLang.Count; j++)
                {
                    listPerson[i].languageSpoken[j].LanguageId = chkLang[j].LanguageId;
                    forLang[i] = "-";
                    forLang[i] = _languageService.GetLangName(chkLang[j].LanguageId);
                    listPerson[i].languageSpoken[j].Language.LangName = forLang[i];
   //                 listPerson[i].Country.Cname= _countryService.FindById(listPerson[i].CountryId).Cname;
                };
            }
            ViewBag.Language = chkLang;
            
            return View(listPerson);
        }

        [HttpGet]
        public IActionResult Detail()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Create()
        {
            CreatePersonViewModel createPerson = new CreatePersonViewModel();
            List<Language> convLang = _languageService.GetAll();
            List<Country> convCountry = _countryService.GetAll();
            List<City> convCities = _cityService.GetAll();

            ViewBag.Countries = convCountry;
            ViewBag.Cities = convCities;        
            ViewBag.Language = convLang;
            return View (createPerson);
        }

        [HttpPost]
        public IActionResult Create(CreatePersonViewModel personViewModel, int countryId, int cityId)
        {
            var fromLang = HttpContext.Request.Form["Language"];
            var fromCountry = HttpContext.Request.Form["Countries"];
            var fromCity = HttpContext.Request.Form["Cities"];
            ViewBag.Language = _languageService.GetAll();
            List<PersonLanguage> langId = new List<PersonLanguage>();
            List<Language> maxLang = _languageService.GetAll();
            int count = 0;
            for (int i = 0; i < fromLang.Count; i++)
            {
                langId.Add(new PersonLanguage
                {
                    LanguageId = int.Parse(fromLang[count]),
                    Language = _languageService.FindById(int.Parse(fromLang[count])),
                   
                });
                count++;
            }
            if (ModelState.IsValid)
            {
                if (personViewModel != null)
                {
                    personViewModel.CountryId = countryId;
                    personViewModel.CityId = cityId;

                    Person returnPerson = _peopleService.Add(personViewModel, langId);

                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }



        public IActionResult FindPerson()
        {
            List<Person> allPerson = _peopleService.All();
            Person person = new Person();
            for (int i=0; i<allPerson.Count; i++)
            {
                person.Id = allPerson[i].Id;
                person.FirstName = allPerson[i].FirstName;
                person.languageSpoken = allPerson[i].languageSpoken;
                person.LastName = allPerson[i].LastName;
                person.Phone = allPerson[i].Phone;
                person.CountryId = allPerson[i].CountryId;
                person.CtyId = allPerson[i].CtyId;
                ViewBag.Person = allPerson;
            }
            return View(person);
        }

        [HttpPost]
        public IActionResult FindPerson(int id)
        {
            Person searchResult = _peopleService.FindById(id);
            if (id > 0)
            {
                if (searchResult.CtyId > 0)
                {
                    ViewBag.City = _cityService.FindById(searchResult.CtyId);
                }
                if (searchResult.CountryId > 0)
                {
                    Country countryName =
                        _countryService.FindById(searchResult.CountryId);
                    ViewBag.Country = countryName.Cname;
                }
            else
                    {
                        searchResult.FirstName = "";
                        searchResult.Id = 0;

                    }
                    ViewBag.Language = _peopleService.GetLanguage(id);
            }
            return PartialView("_View", searchResult);
        }

        public ActionResult LanguageDetails(int id)
        {
            Language lang = _languageService.FindById(id);
            return PartialView("_ShowLanguage", lang);
            // to do : Return the partial view for the markup you want (for the id)
        }

        [HttpGet]
        public IActionResult Details(List<Person> searchResult)
        {
            List<Person> person = _peopleService.All();

            if (searchResult.Count == 0)
            {
                return View(person);
            }
            else
                return View(searchResult);
        }

        [HttpPost]
        public IActionResult Details(int id)
        {
            Person searchResult = _peopleService.FindById(id);

            PersonViewModel showResult = new PersonViewModel()
            {
                FirstName = searchResult.FirstName,
                LastName = searchResult.LastName,
                Phone = searchResult.Phone,
                CountryId = searchResult.CountryId,
                CityId = searchResult.CtyId,
            };
            ViewBag.Language = _peopleService.GetLanguage(id);
            ViewBag.City = _cityService.FindById(searchResult.CtyId);
            ViewBag.Country = _countryService.FindById(searchResult.CountryId);
            return PartialView ("_PersonDetailView",showResult);
        }

        [HttpGet]
        public IActionResult Searching()
        {

            List<Person> listPerson = new List<Person>();
            try
            {
                listPerson = _peopleService.All();
            }
            catch
            {
                if (listPerson.Count == 0)
                {
                    ModelState.AddModelError("System", "Person List has no record!!!");
                }
                return PartialView("_searchResult",listPerson);
            }
               return View();
        }

        [HttpPost]

        public IActionResult Searching(string firstName, string lastName, int countryId, int cityId )
        {
            List<Person> peopleSearch = _peopleService.Search(firstName, lastName, cityId, countryId);
            if (peopleSearch!=null)
            {
                Person showPerson = new Person();
                for (int i=0; i<peopleSearch.Count; i++)
                {
                    showPerson.Id = peopleSearch[i].Id;
                    showPerson.FirstName = peopleSearch[i].FirstName;
                    showPerson.LastName = peopleSearch[i].LastName;
                    showPerson.Phone = peopleSearch[i].Phone;
                    showPerson.CtyId = peopleSearch[i].CtyId;
                    showPerson.CountryId = peopleSearch[i].CountryId;
                    showPerson.languageSpoken = peopleSearch[i].languageSpoken;

                }
                List<Person> listPerson = _peopleService.All();
            string[] forLang = new string[listPerson.Count];
            List<PersonLanguage> chkLang = new List<PersonLanguage>();
            for (int i = 1; i < listPerson.Count - 1; i++)
            {

                listPerson[i].Country = _countryService.FindById(listPerson[i].CountryId);
                chkLang = _peopleService.GetLanguage(listPerson[i].Id);
                for (int j = 0; j < chkLang.Count; j++)
                {
                    listPerson[i].languageSpoken[j].LanguageId = chkLang[j].LanguageId;
                    forLang[i] = "-";
                    forLang[i] = _languageService.GetLangName(chkLang[j].LanguageId);
                    listPerson[i].languageSpoken[j].Language.LangName = forLang[i];
                    //                 listPerson[i].Country.Cname= _countryService.FindById(listPerson[i].CountryId).Cname;
                };
            }
                ViewBag.Language = chkLang;
                return PartialView ("_SearchResult", peopleSearch);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {

WebAssignmentMVC-Louis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" charset="UTF-8" />
    <title>Louis @ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Person Library</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person</a>
                            </li>


                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">Cities</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Index">Language</a>
                            </li>
                        }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Zone</a>
                                </li>
                            }
                            <li class="nav-item">
                                <p class="nav-link text-dark">@User.Identity.Name</p>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
        @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Person Information(Louis Lim) - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/people.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebAssignmentMVC-Louis/Views/Shared/_PersonDetailView.cshtml
@model WebAssignmentMVC.Models.Person.ViewModels.PersonViewModel

@if (Model != null)
            {
<table class="col-2" width="500px">
    <tr>
        <th>ID Number:</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>First Name:</th>
        <td>@Model.FirstName</td>
    </tr>
    <tr>
        <th>Last Name:</th>
        <td>@Model.LastName</td>
    </tr>
    <tr>
        <th>Telephone:</th>
        <td>@Model.Phone</td>
    </tr>
    <tr>
        <th>Country</th>
        <td>@ViewBag.Country</td>
    </tr>
    <tr>
        <th>Country</th>
        <td>@ViewBag.City</td>
    </tr>
    <tr>
        <th>Language</th>
        <td>
            @*@Html.DropDownList("Language", ViewBag.Language as IEnumerable<SelectListItem>);*@
        </td>
    </tr>
    <tr>
        <th>Actions</th>
        <td>
            <a class="btn btn-info" asp-action="Delete" asp-controller="Person" asp-route-id="@Model.Id">Delete</a>
        </td>
    </tr>
</table>
}
else
            {

<p>------</p>
            }

WebAssignmentMVC-Louis/Views/Shared/_PersonList.cshtml
@model Person

    <table class="contact">
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Telephone</th>
            <th>Country</th>
            <th>City</th>
            <th>Actions</th>
            <th>Language</th>
        </tr>
        <tbody>
    <tr>
        <td>@Model.Id</td>
        <td>@Model.FirstName</td>
        <td>@Model.LastName</td>
        <td>@Model.Phone</td>
        <td>@ViewBag.Country</td>
        <td>@ViewBag.City</td>
        <td>
            @foreach (PersonLanguage item in ViewBag.Language)
            {
                @item.LanguageId
            }
        </td>
        <td>
            <a class="btn btn-info" asp-action="Delete" asp-controller="Person" asp-route-id="@Model.Id">Delete</a>
            <button onclick="findThroughId('@Url.Action("Edit", "Person", new { id = Model.Id})')">Edit</button>
        </td>
     </tr>
     </tbody>
</table>

WebAssignmentMVC-Louis/Views/Shared/_SearchResult.cshtml
@model List<Person>

<table class="contact">
    <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Telephone</th>
        <th>Country</th>
        <th>City</th>
        <th>Actions</th>
        <th>Language</th>
    </tr>
    <tbody>
        @if (Model != null)
        {
            @foreach (Person person in Model)
            {
                <tr>
                    <td>@person.Id</td>
                    <td>@person.FirstName</td>
                    <td>@person.LastName</td>
                    <td>@person.Phone</td>
                    <td>@ViewBag.Country</td>
                    <td>@ViewBag.City</td>
                    <td>
                        @foreach (PersonLanguage item in ViewBag.Language)
                        {
                            @item.LanguageId
                        }
                    </td>
                    <td>
                        <a class="btn btn-info" asp-action="Delete" asp-controller="Person" asp-route-id="@person.Id">Delete</a>
                        <a class="btn btn-info" asp-action="Edit" asp-controller="Person" asp-route-id="@person.Id">Edit</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
        }
    </tbody>
 </table>

WebAssignmentMVC-Louis/Views/Shared/_ShowLanguage.cshtml
@model Language

    <td>@Model.Id-@Model.LangName</td>

WebAssignmentMVC-Louis/Views/Shared/_View.cshtml
@model WebAssignmentMVC.Models.Person.Person


<h4>Person Information</h4>
 <hr />

@if (Model != null)
{
<table class="contact" width="500px">
    <tr>
        <th>ID Number:</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>First Name:</th>
        <td>@Model.FirstName</td>
    </tr>
    <tr>
        <th>Last Name:</th>
        <td>@Model.LastName</td>
    </tr>
    <tr>
        <th>Telephone:</th>
        <td>@Model.Phone</td>
    </tr>
    <tr>
        <th>Country</th>
        <td>@ViewBag.Country</td>
    </tr>
    <tr>
        <th>City</th>
        <td>@ViewBag.City</td>
    </tr>
    <tr>
        <th>Language</th>
        <td>
            @foreach (PersonLanguage item in ViewBag.Language)
            {
                @if (item.LanguageId > 0)
                {
                    <a asp-action="LanguageDetails" asp-route-id="@item.LanguageId">Language</a>
        @*                <button onclick="findLanguageId('@Url.Action("LanguageDetails", "Person"),
    new { id=@item.LanguageId})', 'inputId')" class="button">Language List</button>*@

                }
            }
            <div id="languageView"></div>
        </td>
            </tr>
            <tr>
                <th>Actions</th>
                <td>
                    <a class="btn btn-info" asp-action="Delete" asp-controller="Person" asp-route-id="@Model.Id">Delete</a>
                    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
                </td>
            </tr>
        </table>
     <a asp-action="FindPerson">Back to Find by ID</a>
}
else
{

    <p>------</p>
}